/**
 * useKgoose - React hooks for calling external APIs via the G2 fetch proxy.
 * DO NOT MODIFY - Auto-generated by Block App Kit
 *
 * These hooks wrap g2Get/g2Post from kgoose.ts with React loading/error state.
 */

import { useState, useCallback } from 'react'
import { g2Get, g2Post } from '../lib/kgoose'

interface UseKgooseResult<T> {
  /** Call an external API. GET if no body, POST if body provided. */
  callService: (url: string, extension: string, body?: Record<string, unknown>) => Promise<T>
  isLoading: boolean
  error: Error | null
  data: T | null
  reset: () => void
}

/**
 * Generic hook for calling external APIs with loading/error state.
 *
 * @example
 * const { callService, isLoading, data } = useKgoose()
 * // GET:
 * await callService('https://api.datadoghq.com/api/v1/monitor', 'datadog')
 * // POST:
 * await callService('https://slack.com/api/chat.postMessage', 'slack', { channel: '#general', text: 'Hi' })
 */
export function useKgoose<T = unknown>(): UseKgooseResult<T> {
  const [isLoading, setIsLoading] = useState(false)
  const [error, setError] = useState<Error | null>(null)
  const [data, setData] = useState<T | null>(null)

  const callService = useCallback(async (
    url: string,
    extension: string,
    body?: Record<string, unknown>
  ): Promise<T> => {
    setIsLoading(true)
    setError(null)

    try {
      const result = body
        ? await g2Post<T>(url, extension, body)
        : await g2Get<T>(url, extension)
      setData(result)
      return result
    } catch (err) {
      const e = err instanceof Error ? err : new Error(String(err))
      setError(e)
      throw e
    } finally {
      setIsLoading(false)
    }
  }, [])

  const reset = useCallback(() => {
    setIsLoading(false)
    setError(null)
    setData(null)
  }, [])

  return { callService, isLoading, error, data, reset }
}

/**
 * Hook for Slack operations.
 *
 * @example
 * const { sendMessage, isLoading } = useSlack()
 * await sendMessage('#general', 'Hello!')
 */
export function useSlack() {
  const { callService, ...rest } = useKgoose()
  return {
    ...rest,
    sendMessage: (channel: string, text: string) =>
      callService('https://slack.com/api/chat.postMessage', 'slack', { channel, text }),
    postToThread: (channel: string, threadTs: string, text: string) =>
      callService('https://slack.com/api/chat.postMessage', 'slack', { channel, thread_ts: threadTs, text }),
  }
}

/**
 * Hook for Linear operations (GraphQL API).
 *
 * @example
 * const { query } = useLinear()
 * await query('{ viewer { id name } }')
 */
export function useLinear() {
  const { callService, ...rest } = useKgoose()
  return {
    ...rest,
    query: (graphqlQuery: string, variables?: Record<string, unknown>) =>
      callService('https://api.linear.app/graphql', 'linear', { query: graphqlQuery, variables }),
  }
}

/**
 * Hook for Airtable operations.
 *
 * @example
 * const { listRecords } = useAirtable()
 * await listRecords('baseId', 'tableName')
 */
export function useAirtable() {
  const { callService, ...rest } = useKgoose()
  return {
    ...rest,
    listRecords: (baseId: string, tableId: string) =>
      callService(`https://api.airtable.com/v0/${baseId}/${tableId}`, 'airtable'),
    createRecord: (baseId: string, tableId: string, fields: Record<string, unknown>) =>
      callService(`https://api.airtable.com/v0/${baseId}/${tableId}`, 'airtable', { records: [{ fields }] }),
  }
}

/**
 * Generic hook for any external service.
 *
 * @example
 * const pd = useProvider('pagerduty', 'https://api.pagerduty.com')
 * await pd.get('/services')
 */
export function useProvider(extension: string, baseUrl: string) {
  const { callService, ...rest } = useKgoose()
  const base = new URL(baseUrl)
  const resolve = (path: string) => {
    const u = new URL(path, base)
    if (u.origin !== base.origin) {
      throw new Error('Path must be relative to baseUrl (origin mismatch)')
    }
    return u.href
  }
  return {
    ...rest,
    get: <T = unknown>(path: string) =>
      callService(resolve(path), extension) as Promise<T>,
    post: <T = unknown>(path: string, body: Record<string, unknown>) =>
      callService(resolve(path), extension, body) as Promise<T>,
  }
}

export default useKgoose
