/**
 * G2 API Helpers - External service access via the G2 fetch proxy.
 * DO NOT MODIFY - Auto-generated by Block App Kit
 *
 * The fetch proxy (g2-fetch-proxy.ts) intercepts all external fetch() calls and
 * routes them through G2, which handles authentication automatically. The
 * X-G2-Extension header tells G2 which service to authenticate with.
 *
 * Use these helpers or plain fetch() with X-G2-Extension.
 */

/**
 * Unwrap the G2 proxy response envelope.
 * The proxy may wrap responses in { success, data, error }.
 */
export function unwrapProxyResponse<T>(raw: Record<string, unknown>): T {
  if ('success' in raw && 'data' in raw) {
    if (!raw.success) {
      throw new Error((raw.error as string) || 'Proxy request failed')
    }
    return raw.data as T
  }
  return raw as T
}

/**
 * Fetch request to an external API via the G2 fetch proxy.
 * Sets X-G2-Extension and Accept headers automatically.
 *
 * @param url - Full URL of the external API endpoint
 * @param extension - G2 extension name for auth (e.g., 'slack', 'datadog')
 * @param init - Standard fetch RequestInit options
 */
export async function g2Fetch(
  url: string,
  extension: string,
  init?: RequestInit
): Promise<Response> {
  const headers = new Headers(init?.headers)
  headers.set('X-G2-Extension', extension)
  if (!headers.has('Accept')) {
    headers.set('Accept', 'application/json')
  }
  const response = await fetch(url, { ...init, headers })
  if (!response.ok) {
    const body = await response.text().catch(() => '')
    throw new Error(`G2 proxy error ${response.status}: ${body}`)
  }
  return response
}

/**
 * GET request with automatic JSON unwrapping.
 *
 * @example
 * const monitors = await g2Get<Monitor[]>('https://api.datadoghq.com/api/v1/monitor', 'datadog')
 */
export async function g2Get<T = unknown>(url: string, extension: string): Promise<T> {
  const response = await g2Fetch(url, extension)
  const raw = (await response.json()) as Record<string, unknown>
  return unwrapProxyResponse<T>(raw)
}

/**
 * POST request with automatic JSON unwrapping.
 *
 * @example
 * await g2Post('https://slack.com/api/chat.postMessage', 'slack', {
 *   channel: '#general',
 *   text: 'Hello from ssantor-intern!'
 * })
 */
export async function g2Post<T = unknown>(
  url: string,
  extension: string,
  body: Record<string, unknown>
): Promise<T> {
  const response = await g2Fetch(url, extension, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(body),
  })
  const raw = (await response.json()) as Record<string, unknown>
  return unwrapProxyResponse<T>(raw)
}
