/**
 * Logger - Structured JSON logging for ssantor-intern
 * DO NOT MODIFY - Auto-generated by Block App Kit
 */

type LogLevel = 'debug' | 'info' | 'warn' | 'error'

interface LogEntry {
  timestamp: string
  level: LogLevel
  app: string
  message: string
  data?: Record<string, unknown>
}

function formatLog(level: LogLevel, message: string, data?: Record<string, unknown>): string {
  const entry: LogEntry = {
    timestamp: new Date().toISOString(),
    level,
    app: 'ssantor-intern',
    message,
  }

  if (data && Object.keys(data).length > 0) {
    entry.data = data
  }

  return JSON.stringify(entry)
}

export const logger = {
  debug(message: string, data?: Record<string, unknown>): void {
    console.debug(formatLog('debug', message, data))
  },

  info(message: string, data?: Record<string, unknown>): void {
    console.info(formatLog('info', message, data))
  },

  warn(message: string, data?: Record<string, unknown>): void {
    console.warn(formatLog('warn', message, data))
  },

  error(message: string, data?: Record<string, unknown>): void {
    console.error(formatLog('error', message, data))
  },
}

export default logger
