/**
 * Database - D1 SQLite wrapper for linear-jira-sync
 * DO NOT MODIFY - Auto-generated by Block App Kit
 */

import type { D1Database, D1Result } from '@cloudflare/workers-types'

let _db: D1Database | null = null

/**
 * Initialize the database from the Cloudflare environment binding.
 * Called automatically by the server middleware.
 */
export function initDB(database: D1Database): void {
  _db = database
}

function getDB(): D1Database {
  if (!_db) {
    throw new Error('Database not initialized. Ensure initDB() is called with the D1 binding.')
  }
  return _db
}

/**
 * Execute a query and return all matching rows.
 *
 * @example
 * const users = await db.query<User>('SELECT * FROM users WHERE active = ?', [true])
 */
export async function query<T = Record<string, unknown>>(
  sql: string,
  params: unknown[] = []
): Promise<T[]> {
  const result = await getDB().prepare(sql).bind(...params).all<T>()
  return result.results
}

/**
 * Execute a query and return the first matching row, or null.
 *
 * @example
 * const user = await db.first<User>('SELECT * FROM users WHERE id = ?', [userId])
 */
export async function first<T = Record<string, unknown>>(
  sql: string,
  params: unknown[] = []
): Promise<T | null> {
  const result = await getDB().prepare(sql).bind(...params).first<T>()
  return result
}

/**
 * Execute a statement (INSERT, UPDATE, DELETE) and return the result.
 *
 * @example
 * const result = await db.execute('INSERT INTO users (name) VALUES (?)', ['Alice'])
 * console.log(result.meta.last_row_id) // ID of inserted row
 */
export async function execute(
  sql: string,
  params: unknown[] = []
): Promise<D1Result> {
  return await getDB().prepare(sql).bind(...params).run()
}

/**
 * Execute multiple statements in a batch.
 *
 * @example
 * await db.batch([
 *   { sql: 'INSERT INTO users (name) VALUES (?)', params: ['Alice'] },
 *   { sql: 'INSERT INTO users (name) VALUES (?)', params: ['Bob'] },
 * ])
 */
export async function batch(
  statements: Array<{ sql: string; params?: unknown[] }>
): Promise<D1Result[]> {
  const prepared = statements.map(({ sql, params = [] }) =>
    getDB().prepare(sql).bind(...params)
  )
  return await getDB().batch(prepared)
}

export const db = {
  init: initDB,
  query,
  first,
  execute,
  batch,
}

export default db
